spring:
  profiles:
    active: dev
    include: secret
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/sinzinet_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    properties:
      format_sql: true
      use_sql_comments: true
      default_batch_fetch_size: 1000
logging:
  level:
    root: INFO